version: '2'
services:
    testing-app:
        image: testing
        external_links:
            - testing-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/testing?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8008:8008
    testing-mysql:
        extends:
            file: mysql.yml
            service: testing-mysql
